FizzBuzz/FizzBuzzTest/Models/FizzBuzz.cs
//-----------------------------------------------------------------------
// <copyright file="FizzBuzz.cs" company="TCS">
//     Company copyright TCS.
// </copyright>
//-----------------------------------------------------------------------
namespace FizzBuzzTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using PagedList;


    public class FizzBuzz
    {

        /// <summary>
        /// Gets or sets Given Input Number
        /// </summary>
        [Required(ErrorMessage = "Please Enter Any Number")]
        [Range(1, 1000, ErrorMessage = "Given Number Should Be Between 1 And 1000")]
        [Display(AutoGenerateField = false,Name = "Enter Number")]

        public int numberGivenByUser { get; set; }


        /// <summary>
        /// Gets or sets list of elements for pagination in view.
        /// </summary>
        public IPagedList<string> paging { get; set; }

        
    }
}

FizzBuzz/FizzBuzzTest/Controllers/FizzBuzzController.cs
//-----------------------------------------------------------------------
// <copyright file="FizzBuzzController.cs" company="TCS">
//     Company copyright TCS.
// </copyright>
//-----------------------------------------------------------------------
namespace FizzBuzzTest.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using FizzBuzzTest.Controllers;
    using FizzBuzzTest.Models;
    using Repository;
    using PagedList;

    public class FizzBuzzController : Controller
    {
       
        /// <summary>
        /// Number Elements to be displayed per page
        /// </summary>
        private int _numberOfRecordsPerPage = 20;

        /// <summary>
        /// FizzBuzz Logic 
        /// </summary>
        private readonly IGetData _getData;
     
        /// <summary>
        /// FizzBuzzTestController Constructor.
        /// </summary>
        /// <param name="getData">validationForFizzBuzzLogic.</param>
        /// <param name="dataFromRepository">dataFromRepository.</param>
        public FizzBuzzController(IGetData getData)
        {
            this._getData = getData;
            
        }

        /// <summary>
        /// Returns ResultView View.
        /// </summary>
        /// <param name="model">model object of type FizzBuzzModel</param>
        /// <param name="page">page of type Integer</param>
        /// <returns>Returns ResultView View</returns>
        [HttpGet]
        public ActionResult ResultView(FizzBuzz model,int page = 1)
        {
            var repoData =_getData.GetResult(model.numberGivenByUser);
            if (repoData.Count != 0)
            {
                model.paging = repoData.ToPagedList(page, this._numberOfRecordsPerPage);
                model.numberGivenByUser = repoData.Count;
            }
            return View("ResultView", model);
        }

        /// <summary>
        /// Set the model object
        /// </summary>
        /// <param name="model">model object of type FizzBuzzModel</param>
        /// <param name="page">page of type Integer</param>
        /// <returns>Returns ResultView View</returns>
        [HttpPost]
        public ActionResult ResultView(FizzBuzz model, int? page)
        {
            int pageNo = page ?? 1;
            if (ModelState.IsValid)
            {
                var outPutList = _getData.GetResult(model.numberGivenByUser);
                if (outPutList != null)
                {
                    model.paging = outPutList.ToPagedList(pageNo, this._numberOfRecordsPerPage);
                }
            }
            return View("ResultView", model);
        }
    }
}

FizzBuzz/FizzBuzzTest/Views/FizzBuzz/ResultView.cshtml
@model FizzBuzzTest.Models.FizzBuzz
@using FizzBuzzTest.HtmlHelper
@using PagedList
@using PagedList.Mvc
@using System.Web.Optimization
@{
    ViewBag.Title = "ResultView";
}
 
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    
<p style="font-family:Verdana"><h1 style="background-color:aquamarine">Application for Fizz Buzz test</h1></p>

@using (Html.BeginForm("ResultView", "FizzBuzz", new { page = 1 }))
{
    <div class="editor-feild">

        <b style="font-family:Verdana">
            @Html.LabelFor(m => m.numberGivenByUser):
            @Html.TextBoxFor(m => m.numberGivenByUser)
        </b>
        <b style="font-size:small;color:red"> @Html.ValidationMessageFor(m => m.numberGivenByUser)</b>
        </div>

    <p>
        <input type="submit" value="Submit" style="height:25px;width:80px;position:relative;left:170px" />
    </p>
}


@{
    if (Model != null && Model.paging != null)
    {
        foreach (var text in Model.paging)
        {
           @FizzBuzzTest.HtmlHelper.TextDisplay.TxtFormat(text)
            <br />
        }

        <div>
            @Html.PagedListPager(Model.paging, page => Url.Action("ResultView", new { page = page,Model.numberGivenByUser }), PagedListRenderOptions.TwitterBootstrapPager)
        </div>
    }
}

<script>
    $('#numberGivenByUser').on('keypress', function (ev) {
        var keyCode = window.event ? ev.keyCode : ev.which;
        //codes for 0-9
        if (keyCode < 48 || keyCode > 57) {
            //codes for backspace, delete, enter
            if (keyCode != 0 && keyCode != 8 && keyCode != 13 && !ev.ctrlKey) {
                ev.preventDefault();
            }
        }
    });
</script>